name: Build ROS2 workspace

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Build with colcon
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install --event-handlers console_cohesion+ 


